os: osx
osx_image: xcode10.2
language: node_js
node_js: '12'
script:
  - npm test
  - npm run dist
env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder